backend:
  name: github
  repo: mabhub/so-vtt

media_folder: static/assets
public_folder: /assets

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: event
    label: Rando VTT
    folder: src/events
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    editor: { preview: false }
    fields:
      - { name: title, label: Titre de l'événement }
      - { name: date, label: Date de l'événement, widget: datetime }
      - { name: commune, label: Lieu de l'événement }
      - { name: departement, label: Département }

      - { name: boucles_vtt, label: Boucles VTT, widget: list, default: ['x km', 'y km'], required: true }
      - { name: boucles_route, label: Boucles Route, widget: list, required: false }
      - { name: boucles_marche, label: Boucles Marche, widget: list, required: false }
      - { name: boucles_trail, label: Boucles Trail, widget: list, required: false }

      - { name: inscriptions, label: Coût de l'inscription, widget: list, default: ['x €'], required: false }
      - { name: link, label: Lien vers l'événement ou l'affiche, required: false }
      - { name: body, label: Description, widget: markdown, required: false }

